### ISSUE TITLE
Unable to find a specification for `WYChart`

### ISSUE THREAD

**Issue by inix** [GeorgeWang03/WYChart#10]
```
pod --version
1.0.1

```

```
cat Podfile
# Uncomment this line to define a global platform for your project

platform :ios, '8.0'

target 'Project' do
    pod 'CocoaLumberjack'
    pod 'AFNetworking', '~> 3.0'
    pod 'HMSegmentedControl'
    pod 'Masonry'
    pod 'SVProgressHUD'
    pod 'IQKeyboardManager'
    pod 'SDWebImage', '~>3.8'
    pod 'MJRefresh'
    pod 'UIWebView+HeaderFooter'
    pod 'UITextView+Placeholder', '~> 1.2'
    pod 'SAMKeychain'
    pod 'FCFileManager'
    pod 'BEMSimpleLineGraph'
    pod 'WYChart'
end

target 'Project Tests' do

end

target 'Project Tests' do

end
```

xcode version: 7.2.1

**Comment by viciwang** [comment]
Maybe you need to update you pod  @inix 
```
pod repo update
```
`WYChat` can find here: [https://cocoapods.org/?q=WYChart](https://cocoapods.org/?q=WYChart).

**Comment by GeorgeWang03** [comment]
thanks @viciwang .
@inix you shou update you pods, or if you ever customized your gem source which default is (https://gems.ruby.org/) etc. , you have to check and guarantee WYChart avaliable in the source.

use `gem source -l` to check which source you currently using
use `gem source --add (a new source) --remove (the old source)` to config source
