### ISSUE TITLE
楼主请教下Touchpoint_001.gif那个效果是怎么实现

### ISSUE THREAD

**Issue by hjblll** [GeorgeWang03/WYChart#16]
~~~

**Comment by GeorgeWang03** [comment]
@hjblll  长按会出现这个效果，代码中必须保证lineView的`touchable`属性为YES,并且图中线段数为1；至于代码上怎么实现这个效果，可以先参照源码，后续会有相关介绍的博文，有兴趣关注[博客](http://blog.oneinbest.com/)，谢谢！

**Comment by hjblll** [comment]
我参照例子设了lineView的touchable属性为YES,并且图中线段数为1，但是长按的时候没有出现那个点，不知道。楼主有没有别的联系方式可以指点一下~~企鹅1369321003

**Comment by GeorgeWang03** [comment]
@hjblll 657241044 你q我吧
