### ISSUE TITLE
折线图上的数据点 能不能在数据点上方或者下方直接显示数据?而不是要触摸后才能出现数据

### ISSUE THREAD

**Issue by ldhios** [GeorgeWang03/WYChart#2]
折线图上的数据点 能不能在数据点上方或者下方直接显示数据?而不是要触摸后才能出现数据

**Comment by GeorgeWang03** [comment]
这个功能暂时还没有。
如果你急于添加，那么建议在源码的‘WYLineChartMainLineView.m’文件中自行添加，在67行，下述代码块中：
//* * * * * * * * * * * * * * * * * * * *//
    //          Draw Moving Point            //
    //* * * * * * * * * * * * * * * * * * * *//

这个建议很好，在下个版本中我会将其作为一个可选特性添加进去。
谢谢你的反馈
