### ISSUE TITLE
nateYAXisView : labels count can't more than line's points count

### ISSUE THREAD

**Issue by ldhios** [GeorgeWang03/WYChart#3]
为什么X轴上的lable个数 和横向参考线的个数不能跟points数组的个数相同呢?

**Comment by GeorgeWang03** [comment]
首先，label个数和横线参考线是可以和points数组个数相同的，分别通过以下代理方法实现：

- (NSInteger)numberOfLabelOnXAxisInLineChartView:(WYLineChartView *)chartView;//该方法为@required

- (NSInteger)numberOfReferenceLineHorizontalInLineChartView:(WYLineChartView *)chartView;//如果没实现该方法，默认情况下为0

考虑到使用者使用时的灵活性，将其作为一项自定义特性。

谢谢你的反馈

**Comment by ldhios** [comment]
我尝试了很多次都不行, 这两个代理方法我直接返回self.points.count .  经常跳转到    NSAssert(labelCount < self.parentView.points.count, @"WYLineChartCoordinateYAXisView : labels count can't more than line's points count");

**Comment by GeorgeWang03** [comment]
@ldhios 
是代理里面的判断处理问题，抱歉！

现在已经修复并提交到master分支／tag 0.1.1

**Comment by ldhios** [comment]
谢谢您的反馈
