### ISSUE TITLE
- (NSInteger)numberOfLabelOnYAxisInLineChartView:(WYLineChartView *)chartView; 对应的数据源方法?

### ISSUE THREAD

**Issue by ldhios** [GeorgeWang03/WYChart#4]
我看到有个required的代理返回Y轴lable个数, 但是我并没有找lable text的数据源的代理. 类似于x轴的(- (NSString *)lineChartView:(WYLineChartView *)chartView contentTextForXAxisLabelAtIndex:(NSInteger)index)?  这是考虑到Y轴上的lable跟 横向参考线功能重叠吗?

**Comment by GeorgeWang03** [comment]
在之前的 0.1.1版本上已经把Y轴label个数的代理方法去掉了，Y轴的label是和referenceLine对应的。考虑到重叠的问题，接下来0.1.2版本会单独对应

**Comment by JackLSH2016** [comment]
楼主希望吧cocoapod里面的库也更新下

**Comment by GeorgeWang03** [comment]
@JackLSH2016 cocoapods 已更新到 0.1.1版本
