### ISSUE TITLE
如果我的points数组里面的只有一个的话,不会绘制.

### ISSUE THREAD

**Issue by ldhios** [GeorgeWang03/WYChart#5]
如果我的points数组里面的只有一个的话,不会绘制这个数据点. 也不会绘制表格的背景色.  这个感觉不合理. 如果我已经return了. 我的minValue是0 . points只有一个数据. 也应该从零绘制到数据点.

**Comment by GeorgeWang03** [comment]
0.1.1之前一个数据点没有绘制出来，在0.1.2会加上去；
目前minValue指的是points里面的最小值，而不是一个随意的值，应该和数据点一致，最大最小值问题在后续版本可能会交给WYChart来做。

**Comment by cherry143** [comment]
Same issue with piechart
