### ISSUE TITLE
x轴的label为什么不能与数据源的个数一样？

### ISSUE THREAD

**Issue by JackLSH2016** [GeorgeWang03/WYChart#8]
比如我有10个数据 ，_chartView.points的数组长度应该为10，这时在(WYLineChartPoint *)lineChartView:(WYLineChartView *)chartView pointReferToXAxisLabelAtIndex:(NSInteger)index代理方法里面设置x轴label的个数为points.count好像不行。

**Comment by JackLSH2016** [comment]
- (NSInteger)numberOfLabelOnXAxisInLineChartView:(WYLineChartView *)chartView在这个代理里面设置为_chartView.points,会直接越界了。按理来说应该不会的。

**Comment by GeorgeWang03** [comment]
@JackLSH2016 你目前是用Cocoapods的吗，如果是的话，由于版本0.1.1更新还没推上去，所以还有问题，稍等我会推上去；github上的版本0.1.1目前是更新了

**Comment by JackLSH2016** [comment]
对的，是用cocoapod，你更新下里面的库

**Comment by JackLSH2016** [comment]
顺便问一下 你这个支持xib和sb吗?

**Comment by GeorgeWang03** [comment]
@JackLSH2016 正在整理最近收到的反馈和bug，整理完会尽快更新到pods。
.xib目前还没涉及到，后续会多加考虑，由于自定义操作比较多，建议暂时还是手动添加或者手动添加到.xib创建的父视图之上。
谢谢你的支持
