### ISSUE TITLE
拖动旋转会崩溃

### ISSUE THREAD

**Issue by tan2547** [GeorgeWang03/WYChart#9]
- (void)setupXYPie{
  
  self.dataArray = [NSMutableArray arrayWithArray:@[@50.7, @200.34, @40.68, @300.41, @200.34, @40.68, @300.41, @200.34, @40.68, @300.41, @200.34, @40.68, @300.41, @200.34, @40.68, @300.41, @200.34, @40.68, @300.41, @200.34, @40.68, @300.41, @200.34, @40.68, @300.41, @200.34, @40.68, @300.41, @200.34, @40.68, @300.41, @200.34, @40.68, @300.41, @200.34, @40.68, @300.41]];
  
  _pieView = [[WYPieChartView alloc] initWithFrame:CGRectMake(0, 70, self.view.width, self.view.width)];
  _pieView.delegate = self;
  _pieView.datasource = self;
  _pieView.rotatable = YES;
  _pieView.selectedStyle = kWYPieChartSectorSelectedNone;
  _pieView.animationStyle = kWYPieChartAnimationOrderlySpreading;
  _pieView.animationDuration = 0.5;
  _pieView.showInnerCircle = YES;
  _pieView.sectorLineWidth = 5;
  _pieView.sectorStrokeColor = [UIColor blackColor];
  _pieView.labelsTextColor = [UIColor redColor];
  _pieView.labelsBackgroundColor = [UIColor yellowColor];
  _pieView.fillByGradient = YES;
  _pieView.values = self.dataArray;
  _pieView.style = kWYPieChartNormalStyle;
  
  _pieView.centerX = self.view.width/2.0;
  
  [self.view addSubview:_pieView];
  [_pieView update];

}
- (NSInteger)numberOfLabelOnPieChartView:(WYPieChartView *)pieChartView{
  return self.dataArray.count;
  }
- (void)pieChartView:(WYPieChartView *)pieChartView didSelectedSectorAtIndex:(NSInteger)index{

}
- (UIColor *)pieChartView:(WYPieChartView *)pieChartView sectorColorAtIndex:(NSInteger)index{
  return Color(arc4random()%255, arc4random()%255, arc4random()%255);
  }
- (NSString *)pieChartView:(WYPieChartView *)pieChartView textForLabelAtIndex:(NSInteger)index{
  return [NSString stringWithFormat:@"货币基金%@:%@",@(index),@"123123123.99"];
  }
- (NSInteger)pieChartView:(WYPieChartView *)pieChartView valueIndexReferToLabelAtIndex:(NSInteger)index{
  return index;
  }

**Comment by tan2547** [comment]
![Uploading 9188E0A3-133D-4118-B79C-5DEF963CBC11.png…]()
设置动画，在更换数据源的时候，刷新UI有时会崩溃，提示 空字符串。
不设置动画，更换数据源，刷新UI不会崩溃

**Comment by GeorgeWang03** [comment]
@tan2547 贴出crash log信息，最好是加上堆栈信息，这样比较好判断一点
